// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fhrxqkzswawlellkiaak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZocnhxa3pzd2F3bGVsbGtpYWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMzMxNjIsImV4cCI6MjA3NjkwOTE2Mn0.qob8dEkayySbz0j2YQmPnIVB6zVCFv68Vvtfa-HVtyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);